config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  get 'messages/show'

  get 'messages/index'

  get 'messages/delete'

  devise_for :users
  get 'news_item/:id' => 'news_items#show', as: 'news_item_show'

  resources :news_items, path: 'admin/news_items', only: [:create, :edit, :destroy, :update, :new] do
    collection do
      get 'index_page', as: 'list'
    end
  end
  get 'news_items' => 'news_items#index', as: 'news_items_list'
  resources :messages, path: 'admin/messages', except: [:new, :edit, :update]
  resources :images, path: 'admin/images', only: [:create, :edit, :destroy, :update, :new, :index]
  root to: 'pages#index'
  resources :admin, only: [:index]
  resources :pages, path: 'admin/pages', only: [:create, :edit, :destroy, :update, :new] do
    collection do
      get 'index_page', as: 'list'
    end
  end
  resources :pages, path: '', only: [:show]
  get ':parent_id/:id' => 'pages#show', :as => 'pages_full'

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :pic, :styles => { :medium => '300x300>'}
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  default_scope { order('created_at DESC') }
end

app/models/page.rb
class Page < ActiveRecord::Base

  extend FriendlyId

  friendly_id :permalink

  has_ancestry

  default_scope { order('place DESC') }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :add_top_menu_vars

  def add_top_menu_vars
    @licence = Page.find_by_id(1)
    @layer_service = Page.find_by_id(2)
    @other_service = Page.find_by_id(30)
    @about = Page.find_by_id(23)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:pic)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :except => [:create]

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.js
      end
    else
      redirect_to :back
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def index
    @messages = Message.select(:id, :name).page(params[:page]).per_page(10)
  end

  def destroy
    @message = Message.find params[:id]
    @message.destroy
    redirect_to messages_path
  end

  private

    def message_params
      params.permit(:name, :phone, :email, :category, :question)
    end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  @sidebar = 'hello'

  def show
    @no_sidebar = true
    @news_item = NewsItem.find params[:id]
  end

  def edit
    @news_item = NewsItem.find(params[:id])
  end

  def update
    @news_item = NewsItem.find params[:id]
    if @news_item.update_attributes (news_item_params)
      redirect_to list_news_items_path
    else
      render :action => :edit
    end
  end

  def index_page
    @news_items = NewsItem.page(params[:page]).per_page(10)
  end

  def index
    @no_sidebar = true
    @news_container = 'newspage'
    @news_items = NewsItem.page(params[:page]).per_page(10)
  end

  def new
    @news_item = NewsItem.new
  end

  def create
    @news_item = NewsItem.new(news_item_params)
    if @news_item.save
      redirect_to list_news_items_path
    else
      render :action => 'new'
    end
  end


  def destroy
    @news_item = NewsItem.find params[:id]
    @news_item.destroy
    redirect_to list_news_items_path
  end

  private

    def news_item_params
      params.require(:news_item).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  def list

  end

  def show
    # @page = Page.find params[:id]
    @page = Page.friendly.find(params[:id])
  end

  def edit
    @page = Page.friendly.find(params[:id])
  end
  
  def update
    @page = Page.friendly.find params[:id]
    if @page.update_attributes (page_params)
      redirect_to list_pages_path
    else
      render :action => :edit
    end
  end

  def index_page
    @pages = Page.page(params[:page]).per_page(10)
  end

  def index
    @pages = Page.all
    @news_items = NewsItem.limit(5)
    render layout: 'index'
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to list_pages_path
    else
      render :action => 'new'
    end    
  end

  def delete
  end

  def destroy
    @page = Page.find params[:id]
    @page.destroy
    redirect_to list_pages_path
  end

  private

  def page_params
    params.require(:page).permit(:name, :permalink, :content, :parent_id, :place, :title, :meta_description)
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_bread_crumns
  end
end

app/helpers/concerns/admin_helper.rb
module Concerns::AdminHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def get_bread_crumbs(page)
    if page.parent
      "#{link_to('Главная', root_path)}  #{link_to page.parent.name, pages_full_path(page.parent.permalink, page.parent.permalink)}  #{page.name}".html_safe
    else
      "#{link_to('Главная', root_path)}  #{page.name}".html_safe
    end
  end
end

app/views/admin/_left_menu.html.erb
<nav class="subnav">
  <ul>
    <li><%= link_to 'Список новостей', list_news_items_path %>
    <li><%= link_to 'Статичные страницы', list_pages_path %>
    <li><%= link_to 'Изображения', images_path %>
    <li><%= link_to 'Отзывы посетителей', messages_path %>
    <hr>
    <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
  </ul>
</nav>

app/views/admin/index.html.erb
<%= render partial: 'admin/left_menu' %>
<div class="container798">


  <h1>Главная</h1>


</div>

app/views/concerns/admin/index.html.erb
<h1>Concerns::Admin#index</h1>
<p>Find me in app/views/concerns/admin/index.html.erb</p>

app/views/images/_form.html.erb
<%= form_for(@image, :html => { :multipart => true }) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, 'error') %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     <p>
      <%= f.label 'Картинка' %>
      <%= f.file_field :pic, class: 'form-control' %>
     </p>
    <%= f.submit 'Опубликовать', :class => 'btn' %>
<% end %>

app/views/images/edit.html.erb
<h1>Редактирование изображения</h1>

<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <div class="breadcrumbs"><%= link_to 'Изображения', images_path %></div>

  <h1>Редактировать изображение</h1>

  <%= render :partial => 'form' %>

</div>

app/views/images/index.html.erb
<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <%= link_to 'Добавить изображение', new_image_path, :class => 'btn addnewpage' %>

  <h1>Изображения</h1>

  <table>
    <thead>
    <tr>
      <th width="349">ID</th>
      <th width="349">Адрес</th>
      <th style="text-align:center">удалить</th>
    </tr>
    </thead>
    <% @images.each do |image| %>
        <tr>
          <td><%= link_to image.id, edit_image_path(image.id) %></td>
          <td><%= image.pic.url %></td>
          <td align="center"><%= link_to 'X', image_path(image.id), :method => :delete %></td>
        </tr>
    <% end %>

  </table>
</div>

app/views/images/new.html.erb
<h1>Редактирование изображения</h1>

<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <div class="breadcrumbs"><%= link_to 'Изображения', images_path %></div>

  <h1>Новое изображение</h1>

  <%= render :partial => 'form' %>

</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_main_menu.html.erb
<nav class="mainav">
    <ul>
        <li class="parent">
            <%= link_to @licence.name, pages_full_path(@licence.permalink, @licence.permalink)  %>
            <ul class="submenu">
                <% @licence.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
        <li class="parent">
            <%= link_to @layer_service.name, pages_full_path(@layer_service.permalink, @layer_service.children.first ? @layer_service.children.first.permalink : @layer_service.permalink)  %>
            <ul class="submenu">
                <% @layer_service.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>            
        </li>
        <li class="parent">
            <%= link_to @other_service.name, pages_full_path(@other_service.permalink, @other_service.children.first ? @other_service.children.first.permalink : @other_service.permalink)  %>
            <ul class="submenu">
                <% @other_service.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>            
        </li>
        <li class="parent">
            <%= link_to @about.name, pages_full_path(@about.permalink, @about.children.first ? @about.children.first.permalink : @about.permalink)  %>
            <ul class="submenu">
                <% @about.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</nav>






<div id="menuzord" class="menuzord red">
    <a href='javascript:void(0)' class='showhide'><em></em><em></em><em></em></a>
    <ul class="menuzord-menu menuzord-left menuzord-indented scrollable">
        <li>
            <%= link_to @licence.name, pages_full_path(@licence.permalink, @licence.children.first ? @licence.children.first.permalink : @licence.permalink)  %>
            <ul class="dropdown">
                <% @licence.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
        <li>
            <%= link_to @layer_service.name, pages_full_path(@layer_service.permalink, @layer_service.children.first ? @layer_service.children.first.permalink : @layer_service.permalink)  %>
            <ul class="dropdown">
                <% @layer_service.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
        <li>
            <%= link_to @other_service.name, pages_full_path(@other_service.permalink, @other_service.children.first ? @other_service.children.first.permalink : @other_service.permalink)  %>
            <ul class="dropdown">
                <% @other_service.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
        <li>
            <%= link_to @about.name, pages_full_path(@about.permalink, @about.children.first ? @about.children.first.permalink : @about.permalink)  %>
            <ul class="dropdown">
                <% @about.children.each do |page_item| %>
                    <li><%= link_to page_item.name, pages_full_path(page_item.parent.permalink, page_item.permalink)  %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</div>


<script type="text/javascript">
 $(function(){
    $("#menuzord").menuzord({
      trigger: 'click',
      indicatorFirstLevel: "+",
      indicatorSecondLevel: "+"
    });
  });
</script>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=640, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : 'Личный юрист' %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'application', :media => 'all' %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'application' %>
  </head>
  <body>
       <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <header>
            <div class="container">
                <address>
                    <a href="tel:+79261643888" class="phone">8 (926) 164-3888<small> (Мск)</small></a>
                    <a href="tel:+78129000760" class="phone">8 (812) 900-0760<small> (Спб)</small></a>
                </address>

                <%= link_to '', root_path, :class => 'logo' %>
                <%= render partial: 'layouts/main_menu' %>

            </div>
        </header>


        <div id="mainslider" class="owl-carousel">

          <div class="item">
            <%= image_tag('slider/slide02.png') %>
            <div class="caption">
              <h1>Лицензирование деятельности<br>и сертификация товаров</h1>
              <p>Получение лицензии на осуществление лицензируемой деятельности — это требование законодательства, поэтому вопрос «зачем нужно лицензирование» здесь не стоит.</p>
              <a href="/alco" class="btn flr">Лицензирование и сертификация</a>
            </div>
          </div>
          <div class="item">
            <%= image_tag('slider/slide03.jpg') %>
            <div class="caption">
              <h1>Сопровождение<br>сделок с недвижимостью</h1>
              <p>Хотите быть уверены, что ваша сделка с недвижимостью<br>в полном порядке? Мы поможем подготовить и оформить<br>все необходимые документы.</p>
              <a href="/registrationandrealestatetransactions" class="btn flr">Услуги для бизнеса</a>
            </div>
          </div>
          <div class="item">
            <%= image_tag('slider/slide01.png') %>
            <div class="caption">
              <h1>Правовое сопровождение<br>вашего бизнеса</h1>
              <p>Надежная команда профессиональных юристов и адвокатов всегда в вашем распоряжении. Мы решаем любые вопросы в срок и в строгой конфиденциальности.</p>
              <a href="/intellectualproperty" class="btn flr">Услуги для бизнеса</a>
            </div>
          </div>

        </div>

       <p class="notice" style="margin:0;"><%= notice %></p>
       <p class="alert" style="margin:0;"><%= alert %></p>

        <div class="white">
            <div class="container940">
                <div class="services">
                    <h2>Чем мы можем быть вам полезны?</h2>
                    <div class="list">
                      <div class="item">
                          <a href="/registrationofcompanies" class="button i1_1"><span>Регистрация компаний<br> и обособленных<br> подразделений</span></a>
                      </div>
                      <div class="item">
                          <a href="/alco" class="button i1_2"><span>Лицензирование<br> деятельности<br>и сертификация товаров</span></a>
                      </div>
                      <div class="item">
                          <a href="/layer_services/entryintosro" class="button i2_1"><span>Вступление в СРО</span></a>
                      </div>
                      <div class="item">
                          <a href="/otherservices/transportationservices" class="button i2_2"><span>Транспортные услуги</span></a>
                      </div>

                      <div class="item">
                          <a href="/lawyer" class="button i3_1"><span>Юридическое<br> представительство в<br> судебных инстанциях</span></a>
                      </div>
                      <div class="item">
                          <a href="/registrationandrealestatetransactions" class="button i3_2"><span>Сопровождение сделок с<br> недвижимостью</span></a>
                      </div>
                      <div class="item">
                        <a href="/otherservices/price" class="button i4_1"><span>Оценка</span></a>
                      </div>
                      <div class="item">
                        <a href="/layer_services/accountant-service" class="button i4_2"><span>Бухгалтерские<br> услуги</span></a>
                      </div>
                    </div>

                </div>
                <div class="partners">
                    <h2>Мы работаем со многими компаниями и предпринимателями, в том числе и с теми, кто занимает прочное место в экономике России.</h2>
                    <div class="logos">
                      <%= image_tag('partners/5.jpg', :class => 'logo') %>
                      <%= image_tag('partners/6.jpg', :class => 'logo') %>
                      <%= image_tag('partners/7.jpg', :class => 'logo') %>
                      <%= image_tag('partners/8.jpg', :class => 'logo') %>
                    </div>
                    <a href="#" class="btn flr">Рекомендации клиентов</a>
                </div>
                <div class="clearFix"></div>

            </div>
        </div>

        <div class="container940">
            <div class="fbform">
                <h2>Задайте вопрос юристу</h2>
                <h5>Бесплатно и конфиденциально</h5>



              <%= form_tag messages_path, :remote => true do %>
                  <%= text_field_tag :name, '', class: 'cut', :placeholder => 'Ваше имя' %>
                  <%= text_field_tag :phone, '', class: 'cut', :placeholder => '+7 ( ) - -' %>
                  <%= text_field_tag :email, '', :placeholder => 'Email' %>
                  <%= select_tag :category, options_for_select(['Выберите категорию вопроса','Лицензирование: алкоголь','Лицензирование: медицина','Лицензирование: фармацевтика','Регистрация недвижимости','Согласования']), include_blank: false %>
                  <%= text_area_tag :question, '', :placeholder => 'Ваш вопрос...' %>
                  <%= submit_tag 'Отправить запрос', :class => 'btn' %>
              <% end %>

            </div>

          <div class="fbform sent" style="display: none">
            <h2>Ваш вопрос отправлен</h2>
            <h5>Спасибо за обращение, мы свяжемся<br> с вами в ближайшее время.</h5>
          </div>

            <div class="news">

                <h1>Новости</h1>

               <%= link_to 'Архив новостей', news_items_list_path, :class => 'archlink' %>

                <% @news_items.each do |news_item| %>
                    <%= link_to news_item_show_path(news_item.id), :class => 'item' do %>
                        <div class="date"><%= l(news_item.created_at) %></div>
                        <div class="intro"><%= news_item.title %></div>
                    <% end %>
                <% end %>
            </div>

        </div>

        <footer>
            <div class="container940">
                <a href="http://maps.yandex.ru/?text=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82%2C%201%2F2%D0%BA1&sll=37.609901%2C55.727136&ll=37.609901%2C55.727136&spn=0.033903%2C0.009688&z=16&l=map" class="btn map" target="_blank">Как добраться?</a>
                <a href="http://maps.yandex.ru/?rtext=~59.922305,30.347345&sll=30.343308,59.922525&sspn=0.045919,0.013961&rtm=atm&source=route&ll=30.343308,59.922525&spn=0.045919,0.013961&z=15&l=map" class="btn map2" target="_blank">Как добраться?</a>
                <address>
                    <div class="address">Москва <span>Ленинский проспект, д. 1/2 корп. 1</span></div>
                    <div class="address">Санкт-Петербург <span>ул.Марата, 57</span></div>
                    <a href="tel:+79261643888" class="phone"><div class="ico"></div> +7 (926) 164-38-88</a>
                    <a href="tel:+78129000760" class="phone"><div class="ico"></div> +7 (812) 900-07-60</a>
                    <!-- div class="worktime">понедельник-пятница 9:00 - 18:30</div -->
                </address>
                <p class="cprt">© 2010—2014, Юридическая компания «Личный Юрист»</p>
            </div>
        </footer>
  </body>
</html>

app/views/messages/create.js.erb
$('.fbform').hide();
$('.fbform.sent').show();

app/views/messages/delete.html.erb
<h1>Messages#delete</h1>
<p>Find me in app/views/messages/delete.html.erb</p>

app/views/messages/index.html.erb
<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <h1>Сообщения пользователей</h1>

  <table>
    <thead>
    <tr>
      <th width="349">Имя</th>

      <th style="text-align:center">удалить</th>
    </tr>
    </thead>
    <% @messages.each do |message| %>
        <tr>
          <td><%= link_to message.name, message_path(message.id) %></td>
          <td align="center"><%= link_to 'X', messages_path(message.id), :method => :delete %></td>
        </tr>
    <% end %>

  </table>
</div>
<%= will_paginate @news_items, :class => 'pagination', :previous_label => 'Назад', :next_label => 'Вперёд' %>

app/views/news_items/index.html.erb
<div class="container798">

  <h1>Архив новостей</h1>


      <% @news_items.each do |news_item| %>
          <%= link_to news_item_show_path(news_item.id), :class => 'item' do %>
              <div class="date"><%= news_item.created_at.to_formatted_s(:short) %></div>
              <div class="intro"><%= news_item.title %></div>
          <% end %>
      <% end %>
</div>

<%= will_paginate @news_items, :class => 'pagination', :previous_label => 'Назад', :next_label => 'Вперёд' %>

app/views/news_items/index_page.html.erb
<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <%= link_to 'Добавить новость', new_news_item_path, :class => 'btn addnewpage' %>

  <h1>Страницы сайта</h1>

  <table>
    <thead>
    <tr>
      <th width="349">Заголовок</th>

      <th style="text-align:center">удалить</th>
    </tr>
    </thead>
    <% @news_items.each do |news_item| %>
        <tr>
          <td><%= link_to news_item.title, edit_news_item_path(news_item.id) %></td>
          <td align="center"><%= link_to 'X', news_item_path(news_item.id), :method => :delete %></td>
        </tr>
    <% end %>

  </table>
</div>
<%= will_paginate @news_items, :class => 'pagination', :previous_label => 'Назад', :next_label => 'Вперёд' %>

app/views/pages/index.html.erb
<h1>Список страниц</h1>
<div class="row">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to "Создать", new_page_path, class: "btn btn-info btn-sm" %>
    </div>
  </div> 
</div>

<table class="table">
  <tr>
    <th>Название страницы</th>
    <th>URL</th>
    <th>&nbsp;</th>
  </tr>
  <% @pages.each do |p| %>
  <tr>
    <td><%= link_to p.name, p %></td>
    <td><%= p.permalink %></td>
    <td>
      <%= link_to 'редактировать', edit_page_path(p) %> /
      <%= link_to 'удалить', p, :method => 'delete' %>
    </td>
  </tr>
  <% end %>  
</table>

app/views/pages/index_page.html.erb
<%= render partial: 'admin/left_menu' %>
<div class="container798">

  <%= link_to 'Добавить сраницу', new_page_path, :class => 'btn addnewpage' %>

  <h1>Страницы сайта</h1>

  <table>
    <thead>
    <tr>
      <th width="349">Заголовок</th>
      <th>раздел</th>
      <th style="text-align:center">удалить</th>
    </tr>
    </thead>
      <% @pages.each do |page| %>
        <tr>
            <td><%= link_to page.name, edit_page_path(page.id) %></td>
            <td><%= page.parent ? page.parent.name : '-' %></td>
            <td align="center"><%= link_to 'X', page_path(page.id), :method => :delete %></td>
        </tr>
  <% end %>

  </table>
</div>
<%= will_paginate @news_items, :class => 'pagination', :previous_label => 'Назад', :next_label => 'Вперёд' %>